package com.nc.demo.db;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.userid
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.passwd
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.username
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.authority
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    private Integer authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.userid
     *
     * @return the value of public.users.userid
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.userid
     *
     * @param userid the value for public.users.userid
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.passwd
     *
     * @return the value of public.users.passwd
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.passwd
     *
     * @param passwd the value for public.users.passwd
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.username
     *
     * @return the value of public.users.username
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.username
     *
     * @param username the value for public.users.username
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.authority
     *
     * @return the value of public.users.authority
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.authority
     *
     * @param authority the value for public.users.authority
     *
     * @mbg.generated Fri Nov 08 11:31:03 JST 2019
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }
}